<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NewLocationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $existing = DB::table('locations')->pluck('name')->map(fn($n) => strtolower(trim($n)))->toArray();

        $locations = [
            // === CIREBON ===
            ['name'=>'Keraton Kasepuhan','category'=>'Alam','address'=>'Jl. Kasepuhan, Kasepuhan, Lemahwungkuk, Cirebon','description'=>'Keraton tertua di Cirebon yang dibangun pada 1527. Menyimpan koleksi benda pusaka, kereta kencana Singa Barong, dan arsitektur campuran Jawa-Tiongkok-Eropa yang megah. Destinasi wajib bagi pecinta sejarah dan budaya.','latitude'=>-6.7253,'longitude'=>108.5568,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Keraton Kanoman','category'=>'Alam','address'=>'Jl. Kanoman, Kanoman, Pekalipan, Cirebon','description'=>'Keraton kedua di Cirebon yang didirikan oleh Sultan Anom I. Memiliki museum berisi peninggalan kerajaan dan suasana khas keraton Jawa pesisir yang tenang untuk healing pikiran.','latitude'=>-6.7281,'longitude'=>108.5530,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Keraton Kacirebonan','category'=>'Alam','address'=>'Jl. Pulasaren, Pekalipan, Cirebon','description'=>'Keraton terkecil di Cirebon yang masih menyimpan warisan budaya dan tradisi kerajaan. Suasananya lebih intim dan tenang, cocok untuk meditasi sejarah dan healing budaya.','latitude'=>-6.7270,'longitude'=>108.5510,'has_toilet'=>1,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Pantai Baro Gebang','category'=>'Pantai','address'=>'Gebang, Cirebon','description'=>'Pantai yang terletak di ujung utara Cirebon dengan pemandangan laut Jawa yang luas. Cocok untuk menikmati sunset sambil melepas penat dengan suasana pesisir yang asri dan alami.','latitude'=>-6.6480,'longitude'=>108.4810,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>0,'has_camping'=>1],
            ['name'=>'Batu Lawang','category'=>'Alam','address'=>'Sedong, Cirebon','description'=>'Formasi tebing batu kapur alami yang menjulang tinggi dengan pemandangan hijau nan memukau. Tempat yang ideal untuk trekking ringan, fotografi alam, dan menenangkan pikiran.','latitude'=>-6.8080,'longitude'=>108.5340,'has_toilet'=>0,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>1],
            ['name'=>'Bukit Gronggong','category'=>'Gunung','address'=>'Patapan, Beber, Cirebon','description'=>'Bukit dengan ketinggian yang menawarkan panorama kota Cirebon dari atas. Terkenal dengan deretan warung kopi dan kuliner malam yang romantis dengan view lampu kota.','latitude'=>-6.7890,'longitude'=>108.5120,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>1,'has_camping'=>0],
            ['name'=>'Cirebon Waterland','category'=>'Alam','address'=>'Jl. Perjuangan No.2, Sunyaragi, Cirebon','description'=>'Taman rekreasi air keluarga dengan berbagai wahana permainan air modern, kolam ombak, dan seluncuran. Tempat sempurna untuk healing bersama keluarga di akhir pekan.','latitude'=>-6.7400,'longitude'=>108.5280,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>1,'has_camping'=>0],
            ['name'=>'Jempol Waterboom','category'=>'Alam','address'=>'Jl. Jempol Raya, Cirebon','description'=>'Waterpark populer di Cirebon dengan kolam renang Olympic dan wahana air. Suasana segar dan hijau membuat tempat ini cocok untuk refreshing dan melepas lelah.','latitude'=>-6.7320,'longitude'=>108.5510,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Waterpark Ciperna','category'=>'Alam','address'=>'Ciperna, Talun, Cirebon','description'=>'Taman air yang dikelilingi pemandangan sawah dan bukit hijau. Menawarkan suasana alami yang menyegarkan pikiran jauh dari hiruk pikuk kota.','latitude'=>-6.7650,'longitude'=>108.5050,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Batik Trusmi','category'=>'Alam','address'=>'Trusmi Wetan, Plered, Cirebon','description'=>'Sentra batik terbesar di Cirebon dengan ratusan showroom batik mega mendung khas. Wisata belanja sekaligus belajar budaya dan proses pembuatan batik tulis.','latitude'=>-6.7140,'longitude'=>108.5350,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>1,'has_camping'=>0],
            ['name'=>'Masjid Agung Sang Cipta Rasa','category'=>'Alam','address'=>'Jl. Kasepuhan, Lemahwungkuk, Cirebon','description'=>'Masjid bersejarah peninggalan Sunan Gunung Jati dengan arsitektur khas abad ke-15. Tempat yang penuh kedamaian untuk healing spiritual dan kontemplasi.','latitude'=>-6.7260,'longitude'=>108.5570,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Masjid Merah Panjunan','category'=>'Alam','address'=>'Jl. Kolot, Panjunan, Lemahwungkuk, Cirebon','description'=>'Masjid kuno dengan dinding bata merah yang menjadi salah satu peninggalan awal penyebaran Islam di Cirebon. Suasananya khusyuk dan sangat cocok untuk healing batin.','latitude'=>-6.7270,'longitude'=>108.5540,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>0,'has_camping'=>0],
            // === INDRAMAYU ===
            ['name'=>'Pantai Balongan Indah','category'=>'Pantai','address'=>'Balongan, Indramayu','description'=>'Pantai berpasir di pesisir Indramayu dengan ombak tenang dan area bermain anak. Menawarkan suasana pesisir yang damai untuk melepas penat dari rutinitas.','latitude'=>-6.3530,'longitude'=>108.3870,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Pulau Biawak','category'=>'Pantai','address'=>'Pulau Biawak, Indramayu','description'=>'Pulau eksotis di Laut Jawa yang dihuni biawak liar dan memiliki mercusuar peninggalan Belanda. Surga tersembunyi untuk snorkeling, diving, dan healing alam terpencil.','latitude'=>-5.9320,'longitude'=>108.3770,'has_toilet'=>0,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>1],
            // === MAJALENGKA ===
            ['name'=>'Curug Sempong','category'=>'Air Terjun','address'=>'Argapura, Majalengka','description'=>'Air terjun tersembunyi di kaki Gunung Ciremai dengan air jernih mengalir dari tebing setinggi 30 meter. Trek menuju curug melewati hutan pinus yang menyegarkan jiwa.','latitude'=>-6.8900,'longitude'=>108.3700,'has_toilet'=>0,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>1],
            ['name'=>'Curug Ibun Pelangi','category'=>'Air Terjun','address'=>'Lemahsugih, Majalengka','description'=>'Air terjun cantik yang memantulkan pelangi di bawah sinar matahari pagi. Dikelilingi vegetasi tropis lebat yang menciptakan suasana healing alami luar biasa.','latitude'=>-6.9200,'longitude'=>108.2600,'has_toilet'=>0,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Goa Lalay','category'=>'Alam','address'=>'Rajagaluh, Majalengka','description'=>'Gua alami yang dihuni kelelawar dengan stalaktit and stalagmit menakjubkan. Petualangan menyusuri gua yang gelap memberikan pengalaman healing adrenalin yang unik.','latitude'=>-6.8600,'longitude'=>108.3200,'has_toilet'=>0,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Terasering Panyaweuyan','category'=>'Alam','address'=>'Argapura, Majalengka','description'=>'Hamparan sawah terasering yang membentuk pola geometris menakjubkan di lereng Gunung Ciremai. Spot foto ikonik Majalengka yang menawarkan ketenangan luar biasa.','latitude'=>-6.8770,'longitude'=>108.3600,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Situ Janawi','category'=>'Alam','address'=>'Argapura, Majalengka','description'=>'Danau kecil alami di dataran tinggi Argapura yang dikelilingi pepohonan rindang. Tempat sempurna untuk piknik tenang dan merenung jauh dari keramaian.','latitude'=>-6.8850,'longitude'=>108.3550,'has_toilet'=>0,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>1],
            ['name'=>'Ciboer Pass','category'=>'Alam','address'=>'Lemahsugih, Majalengka','description'=>'Jalur wisata alam dengan jembatan kayu ikonik melewati hamparan sawah dan kebun teh. Udara sejuk pegunungan dan pemandangan hijau memberikan efek healing instan.','latitude'=>-6.9100,'longitude'=>108.2700,'has_toilet'=>1,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Jembar Waterpark','category'=>'Alam','address'=>'Jl. Raya Timur, Majalengka','description'=>'Taman rekreasi air terbesar di Majalengka dengan berbagai wahana seru untuk segala usia. Tempat healing keluarga yang menyegarkan di hari libur.','latitude'=>-6.8370,'longitude'=>108.2300,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>1,'has_camping'=>0],
            ['name'=>'Paraland Adventure','category'=>'Alam','address'=>'Argapura, Majalengka','description'=>'Destinasi paralayang dan adventure land di dataran tinggi Majalengka. Memacu adrenalin sambil menikmati panorama Gunung Ciremai dan hamparan sawah dari ketinggian.','latitude'=>-6.8800,'longitude'=>108.3650,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>0,'has_camping'=>1],
            // === KUNINGAN ===
            ['name'=>'Hutan Kota Bungkirit','category'=>'Alam','address'=>'Bungkirit, Kuningan','description'=>'Hutan kota yang rindang dengan jogging track dan area piknik di tengah Kuningan. Paru-paru kota yang menawarkan ketenangan hijau untuk healing sehari-hari.','latitude'=>-6.9750,'longitude'=>108.4800,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>1,'has_camping'=>0],
            ['name'=>'Pondok Pinus Palutungan','category'=>'Alam','address'=>'Cisantana, Cigugur, Kuningan','description'=>'Kawasan wisata hutan pinus dengan pondok-pondok kayu yang instagramable. Udara sejuk dan aroma pinus menciptakan suasana healing alami yang sempurna.','latitude'=>-6.8900,'longitude'=>108.4600,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>0,'has_camping'=>1],
            ['name'=>'Telaga Nilem','category'=>'Alam','address'=>'Kaduela, Pasawahan, Kuningan','description'=>'Danau jernih berair kehijauan yang dikelilingi hutan tropis rapat. Suasananya sangat tenang dan cocok untuk memancing atau sekadar duduk menikmati keheningan alam.','latitude'=>-6.9100,'longitude'=>108.4550,'has_toilet'=>1,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Wisata Alam Linggarjati','category'=>'Alam','address'=>'Linggarjati, Cilimus, Kuningan','description'=>'Kawasan wisata bersejarah tempat Perjanjian Linggarjati dengan taman yang rindang dan gedung bersejarah. Perpaduan healing sejarah dan alam yang menyegarkan.','latitude'=>-6.9030,'longitude'=>108.4700,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Bukit Panembongan','category'=>'Gunung','address'=>'Cigugur, Kuningan','description'=>'Bukit dengan gardu pandang yang menawarkan pemandangan 360 derajat Gunung Ciremai dan kota Kuningan. Spot sunrise terbaik untuk healing jiwa di pagi hari.','latitude'=>-6.9000,'longitude'=>108.4750,'has_toilet'=>0,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>1],
            ['name'=>'Situ Cicerem','category'=>'Alam','address'=>'Kaduela, Pasawahan, Kuningan','description'=>'Telaga tersembunyi dengan air sebening kristal berwarna tosca. Salah satu hidden gem Kuningan yang menawarkan ketenangan luar biasa di tengah hutan.','latitude'=>-6.9150,'longitude'=>108.4520,'has_toilet'=>0,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Kebun Raya Kuningan','category'=>'Alam','address'=>'Padabeunghar, Pasawahan, Kuningan','description'=>'Taman botani seluas 154 hektar di lereng Gunung Ciremai dengan koleksi tumbuhan langka. Tempat healing edukatif dengan udara paling sejuk di Kuningan.','latitude'=>-6.9200,'longitude'=>108.4600,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Lembah Cibacang','category'=>'Alam','address'=>'Cilengkrang, Pasawahan, Kuningan','description'=>'Lembah hijau subur dengan sungai jernih dan air terjun kecil yang menyegarkan. Tempat trekking ringan yang cocok untuk healing alam dan detoks digital.','latitude'=>-6.9250,'longitude'=>108.4500,'has_toilet'=>0,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>1],
            ['name'=>'Sukageuri View','category'=>'Gunung','address'=>'Sukageuri, Darma, Kuningan','description'=>'Spot wisata di tepi Waduk Darma dengan hammock dan ayunan menghadap danau. Pemandangan matahari terbenam yang memukau untuk healing pikiran dan jiwa.','latitude'=>-6.9050,'longitude'=>108.5100,'has_toilet'=>1,'has_musholla'=>0,'has_wifi'=>1,'has_camping'=>1],
            ['name'=>'Batu Luhur','category'=>'Gunung','address'=>'Cigugur, Kuningan','description'=>'Formasi batu alam raksasa di puncak bukit dengan pemandangan luas ke segala arah. Energi alamnya terasa kuat, cocok untuk meditasi dan healing spiritual.','latitude'=>-6.8950,'longitude'=>108.4650,'has_toilet'=>0,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Telaga Biru Cicerem','category'=>'Alam','address'=>'Cicerem, Pasawahan, Kuningan','description'=>'Telaga dengan warna air biru jernih yang menakjubkan, dikelilingi pepohonan tropis. Salah satu destinasi healing terpopuler di Kuningan dengan suasana damai.','latitude'=>-6.9180,'longitude'=>108.4480,'has_toilet'=>1,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Hutan Desa Setianegara','category'=>'Alam','address'=>'Setianegara, Cilimus, Kuningan','description'=>'Hutan desa yang dikelilingi masyarakat lokal dengan jalur hiking dan area camping alami. Pengalaman healing otentik berinteraksi langsung dengan alam liar.','latitude'=>-6.8980,'longitude'=>108.4720,'has_toilet'=>0,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>1],
            ['name'=>'Balong Dalem Jalaksana','category'=>'Alam','address'=>'Jalaksana, Kuningan','description'=>'Kolam pemandian air panas alami bersejarah yang dipercaya memiliki khasiat penyembuhan. Tempat healing tradisional Kuningan yang menenangkan tubuh dan pikiran.','latitude'=>-6.9300,'longitude'=>108.4900,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>0,'has_camping'=>0],
            ['name'=>'Bumi Pelangi Kuningan','category'=>'Alam','address'=>'Cigugur, Kuningan','description'=>'Wisata keluarga dengan berbagai wahana permainan dan taman berwarna-warni. Area piknik luas di lingkungan asri pegunungan yang menyegarkan.','latitude'=>-6.8970,'longitude'=>108.4680,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>1,'has_camping'=>0],
            ['name'=>'Taman Cisantana','category'=>'Alam','address'=>'Cisantana, Cigugur, Kuningan','description'=>'Taman wisata alam di lereng Gunung Ciremai dengan hutan pinus, danau buatan, dan flying fox. Destinasi healing keluarga dengan udara pegunungan yang sejuk.','latitude'=>-6.8920,'longitude'=>108.4630,'has_toilet'=>1,'has_musholla'=>1,'has_wifi'=>0,'has_camping'=>1],
            ['name'=>'Wisata Ipukan','category'=>'Alam','address'=>'Jalaksana, Kuningan','description'=>'Kawasan wisata alam tersembunyi dengan air terjun mini dan kolam alami. Suasana pedesaan yang autentik memberikan pengalaman healing jauh dari modernitas.','latitude'=>-6.9350,'longitude'=>108.4850,'has_toilet'=>0,'has_musholla'=>0,'has_wifi'=>0,'has_camping'=>0],
        ];

        $added = 0;
        foreach ($locations as $loc) {
            if (in_array(strtolower(trim($loc['name'])), $existing)) {
                continue;
            }
            DB::table('locations')->insert(array_merge($loc, [
                'rating' => round(rand(38, 49) / 10, 1),
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ]));
            $added++;
        }
    }
}
